---
kind: pipeline
type: docker
name: default

steps:
  - name: build and check
    image: golang:1.18.3
    commands:
      - echo "super" > superbolt
      - df -h
      - go build hello.go

  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: pdobrinskiy/mygo
      auto_tag: true
      auto_tag_suffix: supertest
