---
kind: pipeline
type: docker
name: default

steps:
  - name: build and check
    image: golang:1.18.3
    commans:
      - echo "super" > superbolt
      - df -h
      - go vet .
      - go test -v ./...
